name: hydroponics_node_setup
description: Setup application for Greenglass Hydroponics nodes
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  get: ^4.6.6
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  logger: ^2.2.0
  rxdart: ^0.27.7
  http: ^1.2.1
  flutter_client_sse: ^2.0.1
  web_socket_channel: ^2.4.5

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
