name: hydroponics_framework
description: Core UI components for greenglass-hydroponics mobile and tablet apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  logger: ^2.0.2+1
  get: ^4.6.5
  dart_nats: ^0.6.1
  syncfusion_flutter_gauges: ^21.1.39
  syncfusion_flutter_charts: ^21.2.10
  flutter_svg: ^2.0.5
  equatable: ^2.0.5
  rxdart: ^0.27.7
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/devices.png
    - assets/graph.png
    - assets/log.png
    - assets/recipe.png
    - assets/implementation.png
    - assets/implementation.svg
    - assets/system.png
    - assets/design.png
    - assets/recipe-icon.svg
    - assets/plant.svg


