name: hydroponics_panel
description: Greenglass IoT Hydroponics touch-screen application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dart_nats: ^0.6.1
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  syncfusion_flutter_gauges: ^21.1.39
  syncfusion_flutter_charts: ^21.2.10
  logger: ^2.0.2+1
  flutter_svg: ^2.0.5
  image: ^4.0.17
  intl: ^0.18.0
  uuid: ^3.0.7
  rxdart: ^0.27.7
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  timezone: ^0.9.2
  hydroponics_framework:
    path: ../hydroponics_framework/
  industrial_theme:
    path: ../../flutter/industrial_theme/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
